### ISSUE TITLE
Data node values not displayed correctly

### ISSUE THREAD

**Issue by erboose** [End-to-end-provenance/DDG-Explorer#42]
The version of DDG Explorer currently packaged with RDataTracker in the RDT development branch does not display data node values correctly when clicking on a node. The displayed value appears to be a conflated path plus the actual value.

**Comment by tfjmp** [comment]
1 - It is probably the current master HEAD version (or some older version), is the bug present on the development head?
2 - Could we modify the code so that DDG does not come with the R package, but the installation directory is part of the environment or in a well known place? It will create a lot of trouble in the long run if we have the .jar as part of the package: any fix to DDG-explorer will require a new release of RDataTracker, someone will forget to update the .jar file etc. etc.

**Comment by erboose** [comment]
This problem appears to be confined to Windows and to simple values stored in ddg.txt.

**Comment by blernermhc** [comment]
Fixed

**Comment by tfjmp** [comment]
In which commit was the issue fixed?

**Comment by blernermhc** [comment]
9e99d138322053bd185e325c5aacaaa5944eb8fc
