### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by tfjmp** [End-to-end-provenance/DDG-Explorer#84]
From https://github.com/End-to-end-provenance/RDataTracker/issues/296:

```
The following problems were observed with the current version of development (6/5/2017):

met-real-time.R: Input and output file nodes are orphaned (no edges).

hydro-real-time.R: DDG Explorer is unable to load ddg.json or ddg.txt.

These problems appear to be new and do not occur with the current version of master.
```

After test the JSON is valid, and can be displayed by CamFlow visualiser. The problem is likely to be within DDG explorer parser.

**Comment by blernermhc** [comment]
I am able to load the json file for the met-real-time example fine.  My current suspicion is that the version of DDG Explorer that parses the ValType field is not bundled into RDataTracker.  Looking into that...

The ddg.txt file does not load because the ValType information is not properly quoted.  The entire ValType value is a quoted string but it contains internal quotes that are not backslashed.

I have not looked into the hydro script problems yet.

**Comment by blernermhc** [comment]
The text fix is a simple change to RDataTracker to get the quoting right.  I have the fix but need to wait for the regression tests to be running to push it.
